Repository Nook-Book/Client, pull requests merged in 2025-01, with the labels that each got.

#26 [Setting] axios 세팅
  package-lock.json
  package.json
  src/api/index.ts
Labels: ⚙ Setting

#27 [feat/#12] TextShape 버튼 처음 클릭 시 색상 변경 주의 모달 추가
  src/components/modal/WarningModal.tsx
  src/pages/detailPage/WritePage.tsx
  src/styles/modal/ModalStyle.ts
Labels: ✨ Feature

#35 Feat/33 검색 api
  App.tsx
  package-lock.json
  package.json
  src/api/book/deleteKeyword.ts
  src/api/book/getBestSeller.ts
  src/api/book/getKeyword.ts
  src/api/book/getSearch.ts
  src/assets/data/dummyRecentSearchList.ts
  src/components/search/BestSellerBook.tsx
  src/components/search/BookCollection.tsx
  src/components/search/RecentSearch.tsx
  src/components/search/ResultBookCard.tsx
  src/hooks/book/useBestSeller.ts
  src/hooks/book/useKeyword.ts
  src/hooks/book/useSearch.ts
  src/pages/searchPage/SearchResultPage.tsx
  src/styles/search/BestSellerStyle.ts
  src/types/search/bestbook.ts
  src/types/search/resentSearch.ts
  src/types/search/search.ts
Labels: 🔗 API
