Repository Nook-Book/Client, pull requests merged in 2025-05, with the labels that each got.

#68 [fix/#66] 간편가입, 검색 페이지 qa 수정
  package-lock.json
  package.json
  src/components/search/BookCollection.tsx
  src/components/search/RecentSearch.tsx
  src/components/search/RecentSearchCard.tsx
  src/components/search/SearchHeader.tsx
  src/constans/search/index.ts
  src/hooks/book/useSearch.ts
  src/pages/loginPage/JoinPage.tsx
  src/pages/searchPage/BestSellerPage.tsx
  src/pages/searchPage/SearchPage.tsx
  src/pages/searchPage/SearchResultPage.tsx
  src/styles/search/RecentSearchStyle.ts
  src/styles/search/SearchResultPageStyle.ts
  src/utils/category/bookCategories.ts
  src/utils/search/handleSearch.ts
Labels: 🐞 BugFix

#70 [fix/#67] 3차 QA 오류 수정
  src/api/friend/getFriendNote.ts
  src/api/friend/getFriendNoteList.ts
  src/api/user-Mypage/getMyPageNoteList.ts
  src/components/header/AllNoteHeader.tsx
  src/components/header/NoteHeader.tsx
  src/components/myPage/friendPage/FriendComponent.tsx
  src/components/navBar/MaPageStackNavigation.tsx.tsx
  src/constans/myPage/index.ts
  src/hooks/friend/useFriendNote.ts
  src/pages/detailPage/AllNotePage.tsx
  src/pages/detailPage/NotePage.tsx
  src/pages/detailPage/WritePage.tsx
  src/pages/myPage/FriendSearchResultPage.tsx
  src/pages/myPage/MyReportPage.tsx
  src/types/friend/index.ts
  src/types/navigation/navigation.ts
Labels: 🐞 BugFix

#71 [fix/#67] 첫실행 온보딩 페이지 노출 수정
  src/components/auth/AuthConsumer.tsx
Labels: 🐞 BugFix

#75 feat: 마이컬렉션페이지
  src/components/myPage/collection/MyCollectionDetailItem.tsx
  src/components/navBar/MaPageStackNavigation.tsx.tsx
  src/constans/myPage/index.ts
  src/pages/myPage/MyCollectionDetailPage.tsx
  src/types/mypage/collection.ts
Labels: ✨ Feature

#77 Refector/#76 api url
  src/api/auth/idTokenLogin.ts
  src/api/book/deleteKeyword.ts
  src/api/book/getBestSeller.ts
  src/api/book/getBookDetail.ts
  src/api/book/getKeyword.ts
  src/api/book/getSearch.ts
  src/api/book/getTimerList.ts
  src/api/book/patchBookDetailStatus.ts
  src/api/book/postTimerEnd.ts
  src/api/book/postTimerStart.ts
  src/api/challenge/deleteChallenge.ts
  src/api/challenge/deleteChallengeExit.ts
  src/api/challenge/deleteParticipant.ts
  src/api/challenge/getCalendar.ts
  src/api/challenge/getChallengeDetail.ts
  src/api/challenge/getChallengeList.ts
  src/api/challenge/getInviteList.ts
  src/api/challenge/getParticipant.ts
  src/api/challenge/patchEditChallenge.ts
  src/api/challenge/patchImage.ts
  src/api/challenge/patchOwner.ts
  src/api/challenge/postAcceptChallenge.ts
  src/api/challenge/postParticipant.ts
  src/api/challenge/postRejectChallenge.ts
  src/api/challenge/postWakeUp.ts
  src/api/collection/deleteBook.ts
  src/api/collection/deleteCollection.ts
  src/api/collection/getCurrentList.ts
  src/api/collection/getList.ts
  src/api/collection/postAddBook.ts
  src/api/collection/postNew.ts
  src/api/collection/postOrder.ts
  src/api/friend/getFriend.ts
  src/api/friend/getFriendList.ts
  src/api/note/deleteImage.ts
  src/api/note/getNoteDetail.ts
  src/api/note/getNoteList.ts
  src/api/note/postImage.ts
  src/api/note/postNote.ts
  src/api/note/putEditNote.ts
  src/api/user-Mypage/getNote.ts
  src/api/user-Mypage/getReport.ts
  src/api/user-Mypage/putId.ts
  src/api/user-Mypage/putNickname.ts
  src/api/userBook/getMyCalendar.ts
  src/components/modal/AddParticipantModal.tsx
  src/hooks/mypage/useFriend.ts
  src/pages/challengePage/NewChallengePage.tsx
  src/pages/challengePage/StatusCardDetailPage.tsx
Labels: 🐞 BugFix

#80 build: expo sdk update
  package-lock.json
  package.json
  src/api/auth/expoToken.ts
Labels: 🐞 BugFix, ✨ Feature
